# Generated by Django 5.1 on 2024-08-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_busca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busca',
        ),
    ]
