# Generated by Django 5.1 on 2024-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_delete_busca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('sugestao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
