# Generated by Django 5.1.2 on 2024-10-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_agro_praga_delete_pesquisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praga',
            name='valor',
        ),
    ]
