# Generated by Django 5.1.3 on 2024-12-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0010_alter_praga_causas_alter_praga_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='praga',
            options={'ordering': ['nome'], 'verbose_name': 'Praga', 'verbose_name_plural': 'Pragas'},
        ),
    ]
