# Generated by Django 5.1.3 on 2024-12-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0011_alter_praga_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agro',
        ),
    ]
